GET http://localhost:3000/

###

POST http://localhost:3000/user
Content-Type: application/json

{
    "first_name": "max",
    "last_name": "Musterman",
    "email": "max-mustermann@test.com",
    "password": "Maxtesting2",
}

###

GET http://localhost:3000/user
Authorization: Bearer eyJpjdowih;dougwPIUGIUGFGPW

###

GET http://localhost:3000/user

###

PUT http://localhost:3000/user
Content-Type: application/json

{
    "old_name": "Drews",
    "new_name": "Pikachu"
}


###

DELETE http://localhost:3000/user

###

DELETE http://localhost:3000/user/all
Content-Type: application/json

{
    "condition": "removals",
    "value": "int"
}

###

POST http://localhost:3000/auction
Content-Type: application/json

{
    "auction_id": "0998777",
    "auction_title": "move from France to Berlin",
    "auction_description": "looking for a good moving company",
    "auction_category": "Removals",
    "auction_budget": "3000 EUR",
    "auction_volume": "20cbm",
    "auction_timeline": "20.11 - 22.12.2020",
    auction_move_from: String,
    auction_move_to: String,
    auction_move_from_postcode: Number,
    auction_move_to_postcode: Number,
    auction_move_from_city: String,
    auction_move_to_city: String,
    auction_move_from_country: String,
    auction_move_to_country: String,
    move_on: Date,
    deliver_on: Date,"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "imo@awesome-startup.com",
    "password": "Il0veChick3ns"
}

###

GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmFhNjI3MzU1MTE3NGI0ZTNmOTBhZDMiLCJlbWFpbCI6Imltb0Bhd2Vzb21lLXN0YXJ0dXAuY29tIiwiaWF0IjoxNjA1MDExMzk2LCJleHAiOjE2MDUwMTQ5OTZ9.DN-31jZ-iawPNDIZ4eOi9Rxv3aJTIbwEPN6Zp6BPxgY